#!/bin/sh

if [ $# -ne 2 ]; then
  echo ""
  echo "   sh install.sh <user> <email>"
  echo ""
  exit 1
fi

git clone https://github.com/POV-Ray/povray.git build
export HOME_BUILD=$PWD
cd $HOME_BUILD/build/unix

echo 'Building POV-Ray'
./prebuild.sh > ../prebuild.txt 2> ../prebuild_error.txt

echo 'Configuring POV-Ray, wait a few minutes ..'
cd ..
./configure --prefix=$HOME/POV-Ray COMPILED_BY="$1 <$2>" LIBS="-lboost_system -lboost_thread" > ../configure.txt 2> ../configure_error.txt

echo 'Instaling POV-Ray'
echo 'Please wait, this may take several minutes...'
make check install > ../make.txt 2> ../make_error.txt

echo ''
echo 'POV-Ray installed at:'
echo "     $HOME/POV-Ray/"
echo "     $HOME/POV-Ray/bin/povray"
echo ''

cd ..
rm -fR build/


